## Analyze dataset

In [26]:
import pandas as pd

df = pd.read_excel('transcription_BZK.xlsx')
df

,Ursprungstabelle,Layout class,Filename,CompensationOffice1,CompensationOffice2,CompensationOffice3,Reference to other offices 1,Reference to other offices 2,Reference to other offices 3,Reference to other offices 4,...,Unnamed: 371,Unnamed: 372,Unnamed: 373,Unnamed: 374,Unnamed: 375,Unnamed: 376,Unnamed: 377,Unnamed: 378,Unnamed: 379,Unnamed: 380
0,281er-Tabelle,BY-eigener-Typ,1818_06_07_1_0,Bayerisches\nLandesentschädigungsamt\nMünchen ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,281er-Tabelle,BY-BE-Hauptphase,1819_04_17_1_0,Bayerisches Landesentschädigungsamt,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,281er-Tabelle,BY-BE-Hauptphase,1819_06_06_1_0,Entschädigungsamt Berlin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,281er-Tabelle,HE-Frühe-Phase,1829_08_25_1_0,Hess. Staatsministerium\nDer Minister des Inne...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,281er-Tabelle,BY-BE-Hauptphase,1842_09_27_1_0,Entschädigungsamt Berlin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,Zweite 10er-Tabelle,HH-NI-NRW-SH-Hauptphase (abweichend 2),1924_02_10_60_0,Hildesheim,NaN,NaN,OFD Berlin\n11/7/02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735,Zweite 10er-Tabelle,HB-Spätphase,1924_02_23_48_0,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
736,Erste 10er-Tabelle,HH-NI-NRW-SH-Hauptphase (abweichend 1),1924_02_23_63_0,Landesamt für Wiedergutmachung Bremen,NaN,NaN,,,,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
737,Erste 10er-Tabelle,RLP-Hauptphase (abweichend 3),1924_03_03_162_0,Amt für Wiedergutmachung\nHeckingstr. 31\n5443...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
738,Zweite 10er-Tabelle,HB-Spätphase,1924_03_15_233_0,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# remove Unnamed columns
df = df.loc[:,~df.columns.str.startswith('Unnamed:')]
df

,Ursprungstabelle,Layout class,Filename,CompensationOffice1,CompensationOffice2,CompensationOffice3,Reference to other offices 1,Reference to other offices 2,Reference to other offices 3,Reference to other offices 4,...,VictimBirthName,VictimBirthDate,VictimBirthPlace,VictimLastAddress,VictimDeathDate,VictimDeathPlace,VictimExtraRemarks1,VictimExtraRemarks2,VictimExtraRemarks3,Bemerkung
0,281er-Tabelle,BY-eigener-Typ,1818_06_07_1_0,Bayerisches\nLandesentschädigungsamt\nMünchen ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.6.1868,NaN,NaN,verst.,NaN,NaN,NaN,NaN,NaN
1,281er-Tabelle,BY-BE-Hauptphase,1819_04_17_1_0,Bayerisches Landesentschädigungsamt,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Doppelrolle
2,281er-Tabelle,BY-BE-Hauptphase,1819_06_06_1_0,Entschädigungsamt Berlin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,wie oben,NaN,NaN,NaN
3,281er-Tabelle,HE-Frühe-Phase,1829_08_25_1_0,Hess. Staatsministerium\nDer Minister des Inne...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,25.8.1829,Dresden,"Darmstadt, Hessen, Schloßgartenstr. 47 prt. 1.",NaN,NaN,NaN,NaN,NaN,Doppelrolle
4,281er-Tabelle,BY-BE-Hauptphase,1842_09_27_1_0,Entschädigungsamt Berlin,NaN,NaN,NaN,NaN,NaN,NaN,...,Heilbrunn,27.9.1842,NaN,NaN,verstorben,Herleshausen,Erben: 2,NaN,NaN,Doppelrolle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,Zweite 10er-Tabelle,HH-NI-NRW-SH-Hauptphase (abweichend 2),1924_02_10_60_0,Hildesheim,NaN,NaN,OFD Berlin\n11/7/02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Doppelrolle
735,Zweite 10er-Tabelle,HB-Spätphase,1924_02_23_48_0,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Doppelrolle
736,Erste 10er-Tabelle,HH-NI-NRW-SH-Hauptphase (abweichend 1),1924_02_23_63_0,Landesamt für Wiedergutmachung Bremen,NaN,NaN,,,,,...,,,,,,,NaN,NaN,NaN,Doppelrolle
737,Erste 10er-Tabelle,RLP-Hauptphase (abweichend 3),1924_03_03_162_0,Amt für Wiedergutmachung\nHeckingstr. 31\n5443...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,01.01.1926,CSR,"Fishman Maimon Str. 7 Apt 30, 6423607 Tel-Aviv",25.11.2016,Israel,frühere Rentenakte 25393/neu: 106 394,NaN,NaN,NaN
738,Zweite 10er-Tabelle,HB-Spätphase,1924_03_15_233_0,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Doppelrolle

In [28]:
# analyze for each column how many non NaN values are present
print(df.notnull().sum() / len(df) * 100)

Ursprungstabelle                            100.000000
Layout class                                100.000000
Filename                                    100.000000
CompensationOffice1                          94.993234
CompensationOffice2                           3.924222
CompensationOffice3                           0.270636
Reference to other offices 1                 29.228687
Reference to other offices 2                 23.680650
Reference to other offices 3                 22.868742
Reference to other offices 4                 22.868742
Reference to other persons or institutes     28.822733
extra remarks 1                              64.682003
extra remarks 2                              38.294993
extra remarks 3                               9.066306
extra remarks 4                               0.541272
extra remarks 5                               0.000000
extra remarks 6                               0.000000
extra remarks 7                               0.000000
BZKNr                                        94.722598
ApplicantFirstName                           83.491204
ApplicantLastName                            83.626522
ApplicantAltFirstName                        29.093369
ApplicantBirthName                           41.677943
ApplicantAltLastName                         26.928281
ApplicantBirthDate                           82.002706
ApplicantBirthPlace                          75.507442
ApplicantCurrentAddress                      79.431664
RelationToVictim                             23.274696
ApplicantExtraRemarks1                       54.533153
ApplicantExtraRemarks2                       24.898512
ApplicantExtraRemarks3                        6.765900
VictimFirstName                              57.780785
VictimLastName                               57.780785
VictimAltFirstName                           26.251691
VictimAltLastName                            23.815968
VictimBirthName                              29.093369
VictimBirthDate                              53.856563
VictimBirthPlace                             46.414073
VictimLastAddress                            41.813261
VictimDeathDate                              37.212449
VictimDeathPlace                             35.588633
VictimExtraRemarks1                          12.584574
VictimExtraRemarks2                           1.623816
VictimExtraRemarks3                           0.405954
Bemerkung                                    82.002706
dtype: float64

In [29]:
# add '.jpg' to the file name
df.loc[:, 'Filename'] = df.loc[:, 'Filename'].apply(lambda x: x + '.jpg')

# rename filename to file_name
df = df.rename(columns={'Filename': 'file_name'})

df

,Ursprungstabelle,Layout class,file_name,CompensationOffice1,CompensationOffice2,CompensationOffice3,Reference to other offices 1,Reference to other offices 2,Reference to other offices 3,Reference to other offices 4,...,VictimBirthName,VictimBirthDate,VictimBirthPlace,VictimLastAddress,VictimDeathDate,VictimDeathPlace,VictimExtraRemarks1,VictimExtraRemarks2,VictimExtraRemarks3,Bemerkung
0,281er-Tabelle,BY-eigener-Typ,1818_06_07_1_0.jpg,Bayerisches\nLandesentschädigungsamt\nMünchen ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.6.1868,NaN,NaN,verst.,NaN,NaN,NaN,NaN,NaN
1,281er-Tabelle,BY-BE-Hauptphase,1819_04_17_1_0.jpg,Bayerisches Landesentschädigungsamt,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Doppelrolle
2,281er-Tabelle,BY-BE-Hauptphase,1819_06_06_1_0.jpg,Entschädigungsamt Berlin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,wie oben,NaN,NaN,NaN
3,281er-Tabelle,HE-Frühe-Phase,1829_08_25_1_0.jpg,Hess. Staatsministerium\nDer Minister des Inne...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,25.8.1829,Dresden,"Darmstadt, Hessen, Schloßgartenstr. 47 prt. 1.",NaN,NaN,NaN,NaN,NaN,Doppelrolle
4,281er-Tabelle,BY-BE-Hauptphase,1842_09_27_1_0.jpg,Entschädigungsamt Berlin,NaN,NaN,NaN,NaN,NaN,NaN,...,Heilbrunn,27.9.1842,NaN,NaN,verstorben,Herleshausen,Erben: 2,NaN,NaN,Doppelrolle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,Zweite 10er-Tabelle,HH-NI-NRW-SH-Hauptphase (abweichend 2),1924_02_10_60_0.jpg,Hildesheim,NaN,NaN,OFD Berlin\n11/7/02,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Doppelrolle
735,Zweite 10er-Tabelle,HB-Spätphase,1924_02_23_48_0.jpg,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Doppelrolle
736,Erste 10er-Tabelle,HH-NI-NRW-SH-Hauptphase (abweichend 1),1924_02_23_63_0.jpg,Landesamt für Wiedergutmachung Bremen,NaN,NaN,,,,,...,,,,,,,NaN,NaN,NaN,Doppelrolle
737,Erste 10er-Tabelle,RLP-Hauptphase (abweichend 3),1924_03_03_162_0.jpg,Amt für Wiedergutmachung\nHeckingstr. 31\n5443...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,01.01.1926,CSR,"Fishman Maimon Str. 7 Apt 30, 6423607 Tel-Aviv",25.11.2016,Israel,frühere Rentenakte 25393/neu: 106 394,NaN,NaN,NaN
738,Zweite 10er-Tabelle,HB-Spätphase,1924_03_15_233_0.jpg,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Doppelrolle

In [31]:
# check that all files exists on disk
import os
files_which_do_not_exist = []
for i in df['file_name']:
    file_name = './IE-GT/' + str(i)
    if not os.path.exists(file_name):
        files_which_do_not_exist.append(file_name)
print(len(files_which_do_not_exist))
print(files_which_do_not_exist)

0
[]

In [32]:
# show disjunct values for each column which has less than 50 unique values
for column in df.columns:
    if len(df[column].unique()) < 50:
        print(column)
        print(df[column].unique())

Ursprungstabelle
['281er-Tabelle' '150er-Tabelle' 'Erste 10er-Tabelle'
 'Zweite 10er-Tabelle']
Layout class
['BY-eigener-Typ' 'BY-BE-Hauptphase' 'HE-Frühe-Phase' 'BY-HB-Frühe Phase'
 'NRW-LRB' 'HH-NI-NRW-SH-Hauptphase' 'Gelbe-Hinweiskarte'
 'HH-NI-NRW-SH-Hauptphase (abweichend 2)' 'NRW-Innenministerium'
 'HE-Hauptphase' 'Hinweiskarte_schwarzes_Datum' 'RLP-Hauptphase'
 'Tabellen-Typ\xa0(abweichend)' 'BW-Hauptphase'
 'RLP-Hauptphase (abweichend 2)/Saarland' 'BY-eigener-Typ (abweichend 1)'
 'Hinweiskarte (Mainz/Neustadt)' 'HH-NI-NRW-SH-Hauptphase (abweichend 1)'
 'NRW-Frühe-Phase' 'ABC-Karten'
 'Auskünfte_Statistisches_Landesamt_NRW (abweichend)'
 'RLP-Hauptphase (abweichend 1)' 'NRW-Köln-Art-V' 'HH-Frühe-Phase'
 'RLP-Hauptphase ' 'RLP-Frühe-Phase'
 'Auskünfte_Statistisches_Landesamt_NRW' 'Tabellen-Typ'
 'NRW-Köln-Härtefonds' 'Suchkarte-Hinweiskarte'
 'BY-Spätphase (abweichend 1)' 'Gerichtsurteile' 'HB-Spätphase'
 'Tabellen-Typ (abweichend)' 'NI-Frühe-Phase'
 'HH-NI-NRW-SH-Hauptphase (abweichend 3)' 'BY-Spätphase'
 'RLP-Hauptphase (abweichend 4)' 'BY-Eigener-Typ'
 'RLP-Hauptphase (abweichend 3)' 'BY-eigener-Typ (abweichend 2)']
CompensationOffice2
[nan '<UNK>\nMünchen 2, Arcisstraße 11'
 'b) Der Oberkreisdirektor -Amt für Wiedergutmachung- in Minden.'
 'Reg. Präs.: Köln'
 'b) Derc Oberkreisdirektor - Amt für Wiedergutmachung - in Minden i/W.'
 'Hannover' 'Wiesbaden\nFrankfurt' 'Wiesbaden'
 '2) Der Oberkreisdirektor \n- Amt für Wiedergutmachung - \nin Warburg'
 'Darmstadt'
 'a) Der Regierungspräsident -Dezernat für Wiedergutmachung- in Detmold'
 'Münster' 'Hamburg 1\nAltstädterstr. 8, Sprinkenhof\nFernspr.: 33 16 41'
 'Hamburg 1\nAltstädterstr. 8, Sprinkenhof\n<UNK>' 'KASSEL'
 'Der Regierungspräsident\nDüsseldorf' 'WIESBADEN'
 'Rheinland-Pfalz\nBerlin']
CompensationOffice3
[nan 'b) Der Oberkreisdirektor -Amt für Wiedergutmachung- in Brake i.L.'
 'Saarburg']
Reference to other offices 2
[nan '\xa0' ' 4.1.60'
 'Übernommen am 6.5.65 \nvon Koblenz 415669 (KK lag nicht vor)'
 'Landesrentenbehörde\nNordrhein-Westfalen\n16. AUG. 1063\nDüsseldorf'
 'Diese Akte wurde an das Landesentschädigungsamt Rheinland-Pfalz \nüberwiesen.'
 'VORGANG an Trier \nab<UNK> (s.Schreiben)'
 'Vorgang an Koblenz\nabgeben (s. Schreiben)'
 'Rheinland-Pfalz \nBerlin \n12.5.65'
 'VORGANG an Bundesverw. Amt.\nabgegeben 7.1.63'
 'Bundes Fin. Min. Bonn 25.11.1985']
Reference to other offices 3
[nan '\xa0' 'Hartkopf, Gertie 8.1.04'
 'Hoher Kommissar der \nVereinten Nationen für \nFlüchtlinge 30.11.67']
Reference to other offices 4
[nan '\xa0']
extra remarks 3
[nan 'Rei.' 'Bayern\n18. Juli 1959'
 'DOPPELMELDUNG\nKöln\ngemeldet am: 3.11.55'
 'DOPPELMELDUNG\nBerlin \ngemeldet am: 28. Feb. 1957' 'Str.'
 'Bayerische Kartei' 'A.Z.'
 'DOPPELMELDUNG \nKöln \ngemeldet am: 19. Aug. 1957'
 'Steiner Rosel 30.7.90' 'Az. 82463/VII/24402' 'He'
 'Siehe auch Antrag\nRegister Nr. 17495' '10.7.66'
 'DOPPELMELDUNG\nBundes Fin.Min.Bonn\ngemeldet am: 28.Feb.1966' 'K'
 'Hüttenberger, Friedrich 2.2.03'
 'Urteil des Landgerichts: Frankfurt vom: 20.8.1965\nGZ: 4 Ks 2/63\nSchrb. der Staatsanwaltschaft: " vom: 20.5.1969\nAZ: 4 Ks 2/63'
 'Köln\n31.1.62' '23.1.59/Pla.'
 'DOPPELMELDUNG\nMünster Köln\ngemeldet am: 2.März 1962'
 'München 15.11.77\n\n25.1.78'
 'DOPPELMELDUNG\nDarmstadt\ngemeldet am: 15. Nov. 1965'
 'Darmstadt\n2.Aug.1960']
extra remarks 4
[nan 'Do' 'He' 'Bayerische Kartei']
extra remarks 5
[nan]
extra remarks 6
[nan]
extra remarks 7
[nan]
ApplicantAltLastName
['Held' nan 'Rothstein' '\xa0' 'Mendel' 'Lion' 'Stein' 'Schlicker' 'Levy'
 'Salomon' 'Odenheimer' 'Muehlendorf' 'Fajans' 'verw. Rotenbach' 'Lesser'
 'David' 'Hanf' 'Glasman' 'Spahr' 'Andorn' 'NOWAK' '(fr. Goldstein)'
 'Hornstein' 'Von Ivanow' 'Altmann' 'Voglova' 'Rosenfelder' 'Kauders'
 'Gruenewald' 'Grünewald' 'verw. Lecheler' 'Wieder' 'Karol' 'Dzialoszycki'
 'Zukier' 'Bodenheim']
RelationToVictim
[nan '\xa0' 'Nachlasspfleger' 'Ehefrau' 'Neffe des Erblassers' 'Erbin'
 'Tochter des Erblassers']
ApplicantExtraRemarks2
[nan 'auch 1951' 'auch 1952' 'auch 1953' '\xa0'
 'verstorben im KZ.\nTheresienstadt' 'Antragsteller am 19.2.1953 verstorb'
 'Antragstellerin ist am \n28.1.52 verstorben. Verfahren \ndadurch erledigt.'
 'verw.' 'verstorben' 'für Victor Engel'
 'geb.159.98 Fulda jetzt verehel. Gelley (BEG: 46099)' 'EG 94612a'
 'einger.: 10.10.1949\n14.8.1957/Zi.'
 'Miterbin:\nWainschel Ida\ngeb. ?\nwohnhaft: Newark, Ney Jersey, USA.'
 '(verstorben)'
 'ZPA 20: \nam 22.12.1949 von Kreis-Sonderhilfsausschuß \nAschendorf/Ems'
 'St.Nr.15 01 08 0947' 'St.Nr. 01 01 14 1320'
 'Antrag auf Hinterbliebenenrente vom 05.01.2013\nAblehnende Entscheidung vom 19.07.2013'
 'Antrag auf Hinterbliebenenrente vom 11.05.2011\nAblehnende Entscheidung vom 08.02.2012'
 'St.Nr. 010223 0116' 'alte STNR 120223 0731\nneue STNR 100223 0829'
 'Geburtsdatumsänderung: +. 3.März 1923\nlt.begl. Fotokopie des Ausweises.'
 'Antrag auf Hinterbliebenenrente vom 16.05.2017\nPos. Bescheid vom 15.05.2018']
ApplicantExtraRemarks3
[nan
 'Die Anspruchsberechtigten Erben werden unter folgen-\nde ZK.Nr. geführt.\nTochter Martha Defries unter ZK, 67 907 A (nach der\nMutter ZK. 67 908 A) Tochter Erna Daniel unter \nZK. 67 907 B (nach Mutter ZK. 67 908 B) Schwieger-\nTochter Gertrud Rosenfeld ZK. 67 907 C (nach der \nSchwiegermuter ZK. 67908 C.'
 '\xa0' 'Ehefrau' '(EG: 94612a)'
 'Claire <jetzt verehl. Gelley (BEG 46.099)' '-Tochter-'
 'alte STNr. 030123 0832\nneue STNr. 030323 0836']
VictimAltFirstName
[nan 'Stanislaw' '\xa0' 'Isaak' 'Maurycy' 'Olga' 'Jacob' 'Heinrich' 'Haim'
 'Moses' 'Johann' 'Jos.' 'Heinz' 'Alexander' 'Albert' 'Pauline'
 'Emil Wilhelm' 'Hermann Paul' 'Wilhelm' 'Frida Elise' '(früher Saly)'
 'Wilhelm Franz' 'Arkadie' 'Hermann' 'Mathilde' 'Bella' 'Kuperminc'
 'Estera' 'August' 'Isaac' 'Theresia' 'B.' 'Louis']
VictimAltLastName
[nan '\xa0' 'Liebenschütz' 'Schertok' 'Unfanger' 'Calka' 'Leinwoll'
 'Jastrzak' 'Kumer' 'Selecnik' 'HELLWIG' 'Thönissen' 'Geratz' 'Weinberg'
 'Nisenbaum' 'Ajzensztejn' 'Bajkina' 'Shub']
VictimExtraRemarks2
[nan 'Erben: ?' 'siehe unter: Lichtenstädter Karl' 'Strauss'
 'Anna Berner, Fr. Pahlke, Gustav Pahlke, Hedwig Chlench' ' (Ehemann)'
 'weitere Erben: unbekannt'
 'Strauss, Aron geboren 24.9.1874 in Michelstadt\ngestorben: Deportiert u. verschollen (Genaue Dat. u. Ort können nicht angegeben werden)'
 'Deportiert u. verschollen/Genaue Dat. u. Ort k. n. angegeb. werd.'
 'Vermerk: Die Obige hat ihren früheren Familienn\n(Schlodinski) wieder angenommen. '
 'Namen weiterer Erben oder Hinterbliebener: Hilda Blum geb. Bruck (22.6.88), \nCharlotte Dornacher geb. Blum (23.11.78), Paul Loeb (30.3.08)'
 'Namen weiterer Erben oder Hinterbliebener: Alfred J. Weil (11.9.1898) und 5 andere'
 '(OG. hat seinen Namen geändert. Früher: Reiser Friedrich, geb. w.o.']
VictimExtraRemarks3
[nan
 'Hirsch, Hans -Sohn- \ngeb. 4.3.1918 in Cottbus \nTel-Aviv/Israel, Shlomo Hamelechstr. 60'
 '<UNK>'
 'Die Registerkarte Nr. 2911 Hartkopf geb. Strauss, Gertie und nach Eheleuten Aron und Lina Strauss ist zu vernichten.']
Bemerkung
[nan 'Doppelrolle' '\xa0' 'mehrere Antragsteller  bzw. Verfolgte'
 'mehrere Antragsteller und Verfolgte'
 'Doppelrolle\nmehrere Antragsteller  bzw. Verfolgte']

In [34]:
#selected_columns = ['Filename', 'CompensatioOffice1', 'extra remarks 1', 'BZKNr', 
#                    'ApplicantFirstName', 'ApplicantLastName', 'ApplicantBirthName', 'ApplicantBirthDate', 'ApplicantBirthPlace', 'ApplicantCurrentAddress', 'ApplicantDeathDate', 'ApplicantDeathPlace',
#                    'VictimFirstName',    'VictimLastName',    'VictimBirthName',    'VictimBirthDate', 'VictimBirthPlace',       'VictimDeathDate', 'VictimDeathPlace']
selected_columns = ['file_name', 'CompensationOffice1', 'BZKNr', 
                    'ApplicantFirstName', 'ApplicantLastName', 'ApplicantBirthName', 'ApplicantBirthDate', 'ApplicantBirthPlace', 'ApplicantCurrentAddress',
                    'VictimFirstName',    'VictimLastName',    'VictimBirthName',    'VictimBirthDate', 'VictimBirthPlace',       'VictimDeathDate', 'VictimDeathPlace']
df_selected = df[selected_columns]
df_selected

,file_name,CompensationOffice1,BZKNr,ApplicantFirstName,ApplicantLastName,ApplicantBirthName,ApplicantBirthDate,ApplicantBirthPlace,ApplicantCurrentAddress,VictimFirstName,VictimLastName,VictimBirthName,VictimBirthDate,VictimBirthPlace,VictimDeathDate,VictimDeathPlace
0,1818_06_07_1_0.jpg,Bayerisches\nLandesentschädigungsamt\nMünchen ...,67800/II/6065,Margarete,Feichtmayer,NaN,7.6.1818,NaN,"Regensburg, Königstr. 2/I",Dr. Heinrich,Held,NaN,6.6.1868,NaN,verst.,NaN
1,1819_04_17_1_0.jpg,Bayerisches Landesentschädigungsamt,BEG 069 657,Etz,Polak,NaN,17.4.1819,Ruskowa,"170 Clymer Street, Brooklyn, N.Y. \nUSA",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1819_06_06_1_0.jpg,Entschädigungsamt Berlin,363801,Cirl,Kraushar,NaN,6.6.1819,Drohobycz,"London N.W.3/England, 109 Green Hill",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1829_08_25_1_0.jpg,Hess. Staatsministerium\nDer Minister des Inne...,12435,NaN,NaN,NaN,NaN,NaN,NaN,Alexander,Martin,NaN,25.8.1829,Dresden,NaN,NaN
4,1842_09_27_1_0.jpg,Entschädigungsamt Berlin,62 507,NaN,NaN,NaN,NaN,NaN,NaN,Emma,Levy,Heilbrunn,27.9.1842,NaN,verstorben,Herleshausen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,1924_02_10_60_0.jpg,Hildesheim,217 980,Kurt,Harnik,NaN,10.2.1924,Dresden,"Philadelphia 25, Pa. \n1923 East Arizona Street",NaN,NaN,NaN,NaN,NaN,NaN,NaN
735,1924_02_23_48_0.jpg,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,408-56-10/10/857,Emilia,Jdanova,NaN,23.02.1924,Witebsk/Weissrussland,"28197 Bremen, Kamphofer Damm 35",NaN,NaN,NaN,NaN,NaN,NaN,NaN
736,1924_02_23_63_0.jpg,Landesamt für Wiedergutmachung Bremen,E 10 213,Ralph,Meyer,,23.2.1924,Bremen,"2708 Cortetzon Road, Brooklyn 26 N.Y./USA",,,,,,,
737,1924_03_03_162_0.jpg,Amt für Wiedergutmachung\nHeckingstr. 31\n5443...,510 524,Baruch,Schub,NaN,03.03.1924,NaN,"Ba'it Bakfar, 77 Ben Yehuda St., Kfar Saba/Israel",Nelly,Schub,NaN,01.01.1926,CSR,25.11.2016,Israel
738,1924_03_15_233_0.jpg,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,408-56-10/10/406,Mikhail,Taimanov,NaN,15.03.1924,Pawlograd,"Ellerbuschort 15, 28719 Bremen",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
# replace NaN values with empty string
df_selected = df_selected.fillna('')

# remove all whitespace from cells
df_selected = df_selected.map(lambda x: x.strip() if isinstance(x, str) else x)
df_selected

df_selected

,file_name,CompensationOffice1,BZKNr,ApplicantFirstName,ApplicantLastName,ApplicantBirthName,ApplicantBirthDate,ApplicantBirthPlace,ApplicantCurrentAddress,VictimFirstName,VictimLastName,VictimBirthName,VictimBirthDate,VictimBirthPlace,VictimDeathDate,VictimDeathPlace
0,1818_06_07_1_0.jpg,Bayerisches\nLandesentschädigungsamt\nMünchen ...,67800/II/6065,Margarete,Feichtmayer,,7.6.1818,,"Regensburg, Königstr. 2/I",Dr. Heinrich,Held,,6.6.1868,,verst.,
1,1819_04_17_1_0.jpg,Bayerisches Landesentschädigungsamt,BEG 069 657,Etz,Polak,,17.4.1819,Ruskowa,"170 Clymer Street, Brooklyn, N.Y. \nUSA",,,,,,,
2,1819_06_06_1_0.jpg,Entschädigungsamt Berlin,363801,Cirl,Kraushar,,6.6.1819,Drohobycz,"London N.W.3/England, 109 Green Hill",,,,,,,
3,1829_08_25_1_0.jpg,Hess. Staatsministerium\nDer Minister des Inne...,12435,,,,,,,Alexander,Martin,,25.8.1829,Dresden,,
4,1842_09_27_1_0.jpg,Entschädigungsamt Berlin,62 507,,,,,,,Emma,Levy,Heilbrunn,27.9.1842,,verstorben,Herleshausen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,1924_02_10_60_0.jpg,Hildesheim,217 980,Kurt,Harnik,,10.2.1924,Dresden,"Philadelphia 25, Pa. \n1923 East Arizona Street",,,,,,,
735,1924_02_23_48_0.jpg,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,408-56-10/10/857,Emilia,Jdanova,,23.02.1924,Witebsk/Weissrussland,"28197 Bremen, Kamphofer Damm 35",,,,,,,
736,1924_02_23_63_0.jpg,Landesamt für Wiedergutmachung Bremen,E 10 213,Ralph,Meyer,,23.2.1924,Bremen,"2708 Cortetzon Road, Brooklyn 26 N.Y./USA",,,,,,,
737,1924_03_03_162_0.jpg,Amt für Wiedergutmachung\nHeckingstr. 31\n5443...,510 524,Baruch,Schub,,03.03.1924,,"Ba'it Bakfar, 77 Ben Yehuda St., Kfar Saba/Israel",Nelly,Schub,,01.01.1926,CSR,25.11.2016,Israel
738,1924_03_15_233_0.jpg,FREIE HANSESTADT BREMEN\nDer Senator für Arbei...,408-56-10/10/406,Mikhail,Taimanov,,15.03.1924,Pawlograd,"Ellerbuschort 15, 28719 Bremen",,,,,,,

## TODO:
- ApplicantExtraRemarks1 and ApplicantExtraRemarks2 -> marital status (check about how it is written)
- VictimExtraRemarks1 -> verstorben  ()

--------------

- normalized dataset
    - ApplicantBirthDate, VictimBirthDate  -> "YYYY-MM-DD"  format
    - ApplicantBirthPlace, ApplicantCurrentAddress, VictimDeathPlace, VictimLastAddress
        - format:"City, State" (if state is available, otherwise just "City") -> ApplicantBirthPlace (ApplicantBirthPlaceCity), ApplicantCurrentAddress, ApplicantCurrentAddressCity

## Create Dataset

- First split it into train validation test

In [36]:
# split in training , validation and test set (80%, 10%, 10%) 
# stratify by 'Layout class'
from sklearn.model_selection import train_test_split
train, test = train_test_split(df_selected, test_size=0.20, random_state=42, stratify=df_selected['Layout class'])
valid, test = train_test_split(test, test_size=0.50, random_state=42, stratify=df_selected['Layout class'])

train.shape, valid.shape, test.shape

((591, 16), (74, 16), (74, 16))

In [38]:
# create a ImageFolder (huggingface) image dataset
import shutil
import os
import csv

def create_image_folder_dataset(df, folder_name):
    if not os.path.exists(folder_name):
        os.makedirs(folder_name)
    for index, row in df.iterrows():
        file_name = './IE-GT/' + str(row['file_name'])
        if os.path.exists(file_name):
            shutil.copy(file_name, folder_name)
        else:
            print(f"File {file_name} does not exist")
    df.to_csv(folder_name + '/metadata.csv', index=False, quoting=csv.QUOTE_NONNUMERIC)

create_image_folder_dataset(train, './inferable/data/BZK/train')
create_image_folder_dataset(valid, './inferable/data/BZK/valid')
create_image_folder_dataset(test, './inferable/data/BZK/test')